zeebe:
  broker:
    exporters:
      redis:
        className: io.zeebe.redis.exporter.RedisExporter
        jarPath: exporters/zeebe-redis-exporter-jar-with-dependencies.jar
        args:
          # comma separated list of io.zeebe.protocol.record.ValueType to export or empty to export all types
          enabledValueTypes: ""
          
          # comma separated list of io.zeebe.protocol.record.RecordType to export or empty to export all types
          enabledRecordTypes: ""
          
          # Redis Stream prefix
          name: "zeebe"

          # record serialization format: [protobuf|json]
          format: "json"