networks:
  camunda_network:
    driver: bridge

services:
  camunda:
    container_name: camunda_broker
    image: camunda/camunda:8.9.14
    environment:
      # Broker only
      - SPRING_PROFILES_ACTIVE=broker,standalone
      # Enables the embedded gateway on broker startup.
      - ZEEBE_BROKER_GATEWAY_ENABLE=true
      # Disable standard Camunda exporter
      - CAMUNDA_DATA_SECONDARYSTORAGE_TYPE=none
      # Security
      - CAMUNDA_SECURITY_AUTHORIZATIONS_ENABLED=false
      - CAMUNDA_SECURITY_AUTHENTICATION_UNPROTECTEDAPI=true
      # Allow running with low disk space
      - ZEEBE_BROKER_DATA_DISKUSAGECOMMANDWATERMARK=0.998
      - ZEEBE_BROKER_DATA_DISKUSAGEREPLICATIONWATERMARK=0.999
      # Logging
      - ZEEBE_LOG_LEVEL=debug
      # Zeebe Redis Settings
      - ZEEBE_REDIS_REMOTE_ADDRESS=redis://redis:6379
      - ZEEBE_REDIS_TIME_TO_LIVE_IN_SECONDS=900
    ports:
      - "26500:26500"
      - "9600:9600"
    volumes:
      - camunda:/usr/local/camunda/data
      - ../exporter/target/jib/zeebe-redis-exporter-jar-with-dependencies.jar:/usr/local/camunda/exporters/zeebe-redis-exporter-jar-with-dependencies.jar
      - ./application.yaml:/usr/local/camunda/config/application.yaml
    networks:
      - camunda_network
    depends_on:
      - redis

  redis:
    container_name: redis_cache
    image: redis:8-alpine
    ports:
      - "6379:6379"
    networks:
      - camunda_network

volumes:
  camunda:
  elastic:
